# Generated by Django 3.2.6 on 2021-08-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='targetname',
            field=models.CharField(default='', max_length=255, verbose_name='评论目标名称'),
            preserve_default=False,
        ),
    ]
